repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-toml # For pyproject.toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa # Enforce specific noqa annotations (noqa: F401,W203)
      - id: python-use-type-annotations # Enforce type annotations instead of type comments

  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        description: Run flake8 checks on the code
        entry: poetry run flake8
        language: system
        types: [python]
